name: path_data
channels:
  - defaults
  - conda-forge
dependencies:
  - pywavelets
  - numpy
  - pandas
  - plotly
  - scipy
  - conda-forge::lmfit
  - conda-forge::pyxdf
  - ipykernel
  - nbformat
  - pip:
    - kaleido==0.1.0.post1
